### PR TITLE
Search multiple cache keys for a match

### PR DESCRIPTION
**Pull request by ryansch**
This PR makes it so that when specifying multiple cache keys, we actually search through the list and find the longest match. This works with things like:
```yaml
keys:
  - v1-bundler-cache-{{ arch }}-{{ checksum "tests/fixtures/Gemfile.lock" }}
  - v1-bundler-cache-{{ arch }}-
```

It will not work if you intentionally mix non-prefix keys.

### CODE REVIEW

**Review by morganick — COMMENTED** [review]
So you're maintaining a cache key lookup in both bash and ruby?

**Comment by ryansch** [comment]
@morganick Negative. The key lookup is only in ruby.

**Review by morganick — APPROVED** [review]
I wish bash didn't suck to read. So `cache-keys.bash` makes `find_cache` available which calls the ruby `cli` that then calls `FindCache`.

**Comment by ryansch** [comment]
@morganick Exactly! `find_cache` uses the power of docker to run the ruby stuff. It's a pattern I've seen in other buildkite plugins.

**Pull request merged**
